<?php


/**
 * Implementation of hook_menu().
 */
function tags_menu() {
  $items = array();

  $items['tags/manage'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tags_manage_form'),
    'access callback' => 'user_access',
    'access arguments' => array('manage own tags'),
    'file' => 'tags.pages.inc',
    'type' => MENU_CALLBACK
  );

  $items['tags/manage/vocabulary/%/ajax'] = array(
    'page callback' => 'tags_manage_vocabulary_ajax',
    'page arguments' => array(3),
    'access callback' => 'user_access',
    'access arguments' => array('manage own tags'),
    'file' => 'tags.pages.inc',
    'type' => MENU_CALLBACK
  );

  return $items;
}

/**
 * Implementation of hook_perm().
 */
function tags_perm() {
  $perms = array(
    'manage own tags',
  );
  return $perms;
}

/**
 * Implementation of hook_theme()
 */
function tags_theme() {
  return array(
    'tags_manage_form' => array(
      'arguments' => array('form' => array()),
    ),

    'tags_manage_vocabulary_ajax' => array(
      'template' => 'template/manage-vocabulary-ajax',
      'arguments' => array('data'=> NULL),
    ),
  );
}